[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "library for dealing with ipld"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
async-std = "1.5.0"
async-trait = "0.1.29"
byteorder = "1.3.4"
cid = "0.5"
dag-cbor = { version = "0.1.0", path = "dag-cbor" }
dag-cbor-derive = { version = "0.1.0", path = "dag-cbor-derive" }
dag-json = { version = "0.1.0", path = "dag-json", optional = true }
dag-pb = { version = "0.1.0", path = "dag-pb", optional = true }
futures = "0.3.4"
libipld-base = { version = "0.1.0", path = "base" }
libipld-macro = { version = "0.1.0", path = "macro" }
multibase = "0.8.0"
multihash = "0.11.2"
thiserror = "1.0.14"

[dev-dependencies]
criterion = "0.3.1"
proptest = "0.9.5"
model = "0.1.2"

[workspace]
members = [
  "base",
  "dag-cbor",
  "dag-cbor-derive",
  "dag-json",
  "dag-pb",
  "macro",
]

[profile.release]
debug = true

[[bench]]
name = "codec"
harness = false

[[bench]]
name = "store"
harness = false
