[package]
name = "libipld-base"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Base traits and definitions used by ipld codecs."
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
cid = "0.5"
multibase = "0.8.0"
multihash = "0.11.2"
thiserror = "1.0.14"
